### ISSUE TITLE
"trans" vs "translate"

### ISSUE THREAD

**Issue by pfouque** [Kudria/django-fsm-admin2#4]
Hi again,
I noticed you are using "translate" template tag : 
https://github.com/Kudria/django-fsm-admin2/blob/main/fsm_admin2/templates/fsm_admin2/fsm_transition_form.html#L10
But as far as i know it's not working with django 2.2 and you requirement accept from version 2.2 : https://github.com/Kudria/django-fsm-admin2/blob/main/setup.py#L21

**Comment by Kudria** [comment]
Hi!
Thanks for noticing, requirements fixed
